DSW1_EL1_GUTARRA_DIEGO/DSW1_EL1_GUTARRA_DIEGO/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DSW1_EL1_GUTARRA_DIEGO.Entity;
using DSW1_EL1_GUTARRA_DIEGO.Models;

namespace DSW1_EL1_GUTARRA_DIEGO.Controllers
{
    public class EmpleadoController : Controller
    {
        CargoDAO objcar = new CargoDAO();
        DistritoDAO objdis = new DistritoDAO();
        EmpleadoDAO objem = new EmpleadoDAO();

        public ActionResult MantenimientoEmpleado()
        {
            return View(objem.ListarEmpleados().ToList());
        }

        public ActionResult Details(int id)
        {
            return View(objem.BuscarEmpleado(id));
        }
        public ActionResult Create()
        {
            ViewBag.distritos = new SelectList(objdis.ListarDistrito(), "idDistrito", "descripcion");
            ViewBag.cargos = new SelectList(objcar.ListarCargo(), "idCargo", "descripcion");
            return View(new Empleado());
        }

        [HttpPost]
        public ActionResult Create(Empleado reg)
        {
            ViewBag.distritos = new SelectList(objdis.ListarDistrito(), "idDistrito", "descripcion");
            ViewBag.cargos = new SelectList(objcar.ListarCargo(), "idCargo", "descripcion");
            try
            {
                if (ModelState.IsValid)
                {
                    objem.InsertarEmpleado(reg);
                    return RedirectToAction("MantenimientoEmpleado");
                }
                return RedirectToAction("MantenimientoEmpleado");
            }

            catch
            {
                return View();
            }

        }
        public ActionResult Edit(int id)
        {
            Empleado reg = objem.BuscarEmpleado(id);
            ViewBag.distritos = new SelectList(objdis.ListarDistrito(), "idDistrito", "descripcion",reg.idDistrito);
            ViewBag.cargos = new SelectList(objcar.ListarCargo(), "idCargo", "descripcion",reg.idCargo);

            return View(reg);
        }
        [HttpPost]
        public ActionResult Edit(Empleado reg)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objem.ActualizarEmpleado(reg);
                    return RedirectToAction("MantenimientoEmpleado");
                }
                return RedirectToAction("MantenimientoEmpleado");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            Empleado em = objem.BuscarEmpleado(id);
            return View(em);

        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleado em = objem.BuscarEmpleado(id);
            objem.BajaEmpleado(em);
            return RedirectToAction("MantenimientoEmpleado");
        }
    }
}

DSW1_EL1_GUTARRA_DIEGO/DSW1_EL1_GUTARRA_DIEGO/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DSW1_EL1_GUTARRA_DIEGO.Entity;
using DSW1_EL1_GUTARRA_DIEGO.Models;

namespace DSW1_EL1_GUTARRA_DIEGO.Controllers
{
    public class ProductoController : Controller
    {
        ProductoDAO objpro = new ProductoDAO();
        CategoriaDAO objcat = new CategoriaDAO();
        public ActionResult ConsultaProducto(string producto = null, int IdCategoria = 0)
        {
            ViewBag.categorias = new SelectList(objcat.ListarCategorias(), "IdCategoria", "nomCategoria",IdCategoria);
            if (producto == null && IdCategoria == 0)
            {
                return View(objpro.ListarProductos());
            }
            else if (producto == null && IdCategoria != 0)
            {
                return View(objpro.ListarProductos(producto,IdCategoria));
            }
            else{
                return View(objpro.ListarProductos(producto, IdCategoria));
                    
            }

 
        }
     
    }
}

DSW1_EL1_GUTARRA_DIEGO/DSW1_EL1_GUTARRA_DIEGO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
<style>
    .footer-bottom {
        width: 100%;
        padding: 25px 0;
        text-align: center;
        color: #fff;
        background: #333333;
    }
    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 300px;
        margin: auto;
        text-align: center;
        font-family: arial;
    }

    .price {
        color: grey;
        font-size: 22px;
    }

    .card button {
        border: none;
        outline: 0;
        padding: 12px;
        color: white;
        background-color: #333333;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

        .card button:hover {
            opacity: 0.7;
        }
</style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Negocios", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Mantenimiento Empleado", "MantenimientoEmpleado", "Empleado")</li>
                    <li>@Html.ActionLink("Consulta Producto", "ConsultaProducto", "Producto")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr />

    </div>
    <div class="footer-bottom">
        <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>